version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.20
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app
 
  mysql:
   container_name: some-mysql
   image: mysql:5.7
   environment:
    - MYSQL_DATABASE=bulls
    - MYSQL_ROOT_PASSWORD=123456
    #- MYSQL_ROOT_HOST='%'
   volumes:
    #- /usr/local/mysql/conf.d:/etc/mysql/conf.d
    - /usr/local/mysql/data:/var/lib/mysql
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./bulls
    working_dir: /bulls
    volumes:
      - ./bulls:/bulls
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
